{% set version = "1.0rc3" %}

package:
  name: pydensecrf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pydensecrf/pydensecrf-{{ version }}.tar.gz
  sha256: 08be1603af2bede05c7697b6018e8e3059de7cc181e4e784b334889dcc749aa5

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.22
    - msinttypes  # [win and py<35]
  run:
    - python

test:
  requires:
    - numpy
  imports:
    - pydensecrf

about:
  home: http://github.com/lucasb-eyer/pydensecrf
  license: MIT
  summary: "A python interface to Philipp Krähenbühl's fully-connected (dense) CRF code"
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
