appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nlNmfQduyBiTG0zb+wXsQoVgiUdIM/2z7WUVENeMGUVHk/L0hQhnKBqVIwYfEf4+VajlxBA/adn+XjPkYEnhcS3b7pEQB9P2inVruUlLv1SlEEWtTSHTGVjYS/cUXrgPGRtnzbJ3f9Ww+0ceGg1UZJ4EwX9DwWAbius1foPfSbXZc2jXCk48jr0+AYx9NysrgdgbFADtIaJk/TKba4OsCE0z2xwsSkxPI7s5TlQJ8DHG7pXXxu8dILKKgGbNBszXcigo5Q+jDE2LIYskm7oQaqHP8p9LDa22S5sAewpezLUO3y/aonIJHX3TAKuWgcpUN6YH+wxrHIRyDznRefKcnTGyZKdBny0qqAXycqkpAa9fBUjXnJGVnY9ChJgGtWEkRyL80v3xlAF3BSBL9o3wAQ9r6ogIpEd0AY0ToH/czfaQDuvde4z8m2DGY6Js+SD/FvD6zV+JPuTrW0RJL5Up3Wr/eafkiPxnggidFORPh/3gJOlu66J2kvkS4cFPBU8dlWvgVDxOkdrLvs4xx4TZoa4Yo64mkJQGU+Il0FPvyvCJ+2PNQx7hvObrdEWJhN/XS+my/iOb1Vt4zx6ckDzTvbOC1Rpg1GM8pYS3VLbz6AhxdeK7wBdE5WQZskVb75yUIcjO5VTcOXCl2fbT85TVDq+TVaahRGpwB+2vVdr5dsw=}
